[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "telegram-mcp"
version = "1.5.0"
<<<<<<< HEAD
description = "Telegram MCP (Model Context Protocol) server built using Python, Telethon, and MCP Python SDK"
readme = "README.md"
authors = [
    {name = "chigwell"}
=======
description = "Telegram integration for Claude via the Model Context Protocol"
readme = "README.md"
authors = [
    {name = "l1v0n1"}
>>>>>>> 34256575c5ccd1cfa8bf8cf577bfa4fd48429904
]
license = {text = "Apache-2.0"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "mcp[cli]>=1.4.1",
    "nest-asyncio>=1.6.0",
    "python-dotenv>=1.1.0",
    "telethon>=1.39.0",
]

[project.urls]
<<<<<<< HEAD
"Homepage" = "https://github.com/chigwell/telegram-mcp"
"Bug Tracker" = "https://github.com/chigwell/telegram-mcp/issues"
=======
"Homepage" = "https://github.com/l1v0n1/telegram-mcp-server"
"Bug Tracker" = "https://github.com/l1v0n1/telegram-mcp-server/issues"
>>>>>>> 34256575c5ccd1cfa8bf8cf577bfa4fd48429904
