name: Publish Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel
    
    - name: Build package
      run: |
        python -m build
    
    - name: Get version from tag
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
    
    - name: Generate changelog
      id: generate_changelog
      run: |
        git log --pretty=format:"* %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD > CHANGELOG.txt
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        cat CHANGELOG.txt >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        body: |
          # Telegram MCP v${{ steps.get_version.outputs.VERSION }}
          
          ## Changes in this release:
          ${{ steps.generate_changelog.outputs.CHANGELOG }}
          
          ## Installation
          
          ```bash
          git clone https://github.com/${{ github.repository }}.git
          cd telegram-mcp-server
          pip install -r requirements.txt
          ```
          
          See the [README](README.md) for complete documentation.
        draft: false
        prerelease: false
        files: |
          dist/*
          LICENSE
          README.md 